### ISSUE TITLE
Edit Buttons do not show

### ISSUE THREAD

**Issue by renderfarmer** [2sic/app-timelinejs#1]
It seems that in newer versions of 2SXC the edit Buttons for timeline entries do not show. Tested in 9.4.1

**Comment by iJungleboy** [comment]
Did you try it in a newer version of 2sxc - like 9.10?

**Comment by renderfarmer** [comment]
Only up to 9.5 - will try that after the next backup and let you know. Thanks.

**Comment by renderfarmer** [comment]
Just tried with 9.12 - still no edit options. Any idea if it's a random problem or if the APP does not support the newer versions of 2SXC ?

**Comment by iJungleboy** [comment]
should be fixed now in 2sxc 9.33. 
also there are issues with the latest jQuery in newer DNNs, we'll release a new version of the app in a few hours.

**Comment by renderfarmer** [comment]
Sounds good. Will test soon.
