### ISSUE TITLE
Unable to get Timeline working on 2sxc 9.32.1

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/app-timelinejs#2]
I recently installed this app on DNN 9.2.2 with 2sxc 9.32.1. I have tried changing, deleting, adding new records in both the Timeline Settings and Entry but no matter what I do, only 1 entry will appear on the Timeline.
 
I have 2 Timeline Settings entries and 11 Timeline Entries and I can't seem to get anything to appear or work after the 1 entry. Does this app work in 2sxc 9+?

**Comment by iJungleboy** [comment]
There is a bug in many 9x versions which we only discovered and fixed in the upcoming 9.33. Because it was a rarely used feature, only the timeline app is affected. So it will work in 9.33, but don't use the RC 1 yet, because it has larger bug than this one (WIP)
