### ISSUE TITLE
API moved?

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/app-timelinejs#4]
The timeline on the community website stopped working. https://dnncommunity.org/About-DNN/History

It gives a 404 https://dnncommunity.org/api/2sxc/api/2sxc/app-sys/appcontent/GetContentBlockData

We're running DNN 9.6.0 and the 2SXC 10.25.2
The app is App: TimelineJS (v. 01.09.00)

TBH : I'm not sure when this started as I have not visited the page in a while. I just got the feedback from a visitor.

**Comment by iJungleboy** [comment]
We ran into the same issue on 2sic.com (where we use the timeline) and it was a bug in 2sxc 10.2x. Best upgrade to the latest 2sxc 10 or even 11.
